import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { careers, domains } from "../data/careers";
import "./careers.css";

function ExploreCareers() {
  const [query, setQuery] = useState(""); const [domain, setDomain] = useState("All"); const [selected, setSelected] = useState([]);
  const results = useMemo(() => careers.filter((career) => (domain === "All" || career.domain === domain) && `${career.name} ${career.description} ${career.skills.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [domain, query]);
  const toggleCareer = (id) => setSelected((current) => current.includes(id) ? current.filter((careerId) => careerId !== id) : current.length < 4 ? [...current, id] : current);
  return <div className="careers-page"><header className="explore-header"><Link to="/" className="explore-brand">✦ Career<span>CoPilot</span></Link><Link to="/" className="back-dashboard">← Dashboard</Link></header><main className="explore-main"><p className="eyebrow">CAREER DISCOVERY</p><h1>Explore careers, without pressure.</h1><p className="explore-lede">Learn what different paths involve. There is no single “best” career—only options that may fit your interests and goals.</p><div className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search careers, skills, or fields..." /></div><div className="domain-filters">{domains.map((item) => <button key={item} className={domain === item ? "active" : ""} onClick={() => setDomain(item)}>{item}</button>)}</div><div className="results-title"><strong>{results.length} careers to explore</strong><span>Select 2–4 careers to compare</span></div>{results.length ? <div className="career-grid">{results.map((career) => <article className="career-card" key={career.id}><div className="card-domain">{career.domain}</div><h2>{career.name}</h2><p>{career.description}</p><div className="tag-row">{career.skills.slice(0, 3).map((skill) => <span key={skill}>{skill}</span>)}</div><p className="education"><b>Education:</b> {career.education[0]}</p><div className="card-actions"><Link to={`/careers/${career.id}`}>Explore career →</Link><button className={selected.includes(career.id) ? "compare-picked" : ""} onClick={() => toggleCareer(career.id)}>{selected.includes(career.id) ? "✓ Selected" : "+ Compare"}</button></div></article>)}</div> : <div className="empty-state"><span>⌕</span><h2>No careers found</h2><p>Try a different search term or remove a filter.</p><button onClick={() => { setQuery(""); setDomain("All"); }}>Clear filters</button></div>}</main>{selected.length >= 2 && <div className="compare-bar"><span>{selected.length} careers selected</span><Link to={`/compare?careers=${selected.join(",")}`}>Compare careers →</Link></div>}</div>;
}
export default ExploreCareers;
